default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: qwrt4321

development:
  <<: *default
  database: pokemon_development

test:
  <<: *default
  database: pokemon_test